#
#
# Copyright Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Validation Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-prompt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./scripts/python-scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        run: pip3 install -r requirements.txt
      - name: Validate prompt
        run: python3 sync.py -t validate
  validate-yaml:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Use Node.js and cache dependencies
          uses: actions/setup-node@v4
          with:
            node-version: '22.21'
            cache: 'yarn'
        - name: Install dependencies
          run: yarn install --immutable --frozen-lockfile 
        - name: Run Prettier
          run: yarn verify